<?xml version="1.0"?>
<!-- Revolute-Revolute Manipulator -->
<robot name="armbot2_sensor" xmlns:xacro="http://www.ros.org/wiki/xacro">

  <!-- Constants for robot dimensions -->
  <xacro:property name="PI" value="3.1415926535897931"/>
  <xacro:property name="mass" value="1" /> <!-- arbitrary value for mass -->
  <xacro:property name="radius" value="0.04" /> <!-- Cylinder radius -->
  <xacro:property name="height0" value="0.1" /> <!-- Base_Link-->
  <xacro:property name="height1" value="0.5" /> <!-- Link 1 -->
  <xacro:property name="height2" value="0.5" /> <!-- Link 2 -->
  <xacro:property name="sensor_size" value="0.01" /> <!-- Size of square 'camera' box -->
  <xacro:property name="axel_offset" value="0.0" /> <!-- Space btw top of beam and the each joint -->

  <!-- Import all Gazebo-customization elements, including Gazebo colors -->
  <xacro:include filename="$(find armbot2_sensor)/urdf/armbot2_sensor.gazebo" />
  <!-- Import Rviz colors -->
  <xacro:include filename="$(find armbot2_sensor)/urdf/materials.xacro" />

  <!-- Used for fixing robot to Gazebo 'base_link' -->
  <link name="world"/>

  <joint name="joint0" type="fixed">
    <parent link="world"/>
    <child  link="base_link"/>
  </joint>

  <!-- Base Link -->
  <link name="base_link">
    <collision>
      <origin xyz="0 0 ${height0/2}" rpy="0 0 0"/>
      <geometry>
        <cylinder length="${height0}" radius="${radius}"/>
      </geometry>
    </collision>

    <visual>
      <origin xyz="0 0 ${height0/2}" rpy="0 0 0"/>
      <geometry>
	<cylinder length="${height0}" radius="${radius}"/>
      </geometry>
      <material name="orange"/>
    </visual>

    <inertial>
      <origin xyz="0 0 ${height0/2}" rpy="0 0 0"/>
      <mass value="${mass}"/>
      <inertia
	  ixx="${mass / 12.0 * (3*radius*radius + height0*height0)}" ixy="0.0" ixz="0.0"
	  iyy="${mass / 12.0 * (3*radius*radius + height0*height0)}" iyz="0.0"
	  izz="${mass / 2.0  * (radius*radius)}"/>
    </inertial>
  </link>

  <joint name="joint1" type="continuous">
    <parent link="base_link"/>
    <child link="link1"/>
    <origin xyz="0 0 ${height0/2 - axel_offset}" rpy="0 0 0"/>
    <axis xyz="0 0 1"/>
    <dynamics damping="0.7"/>
  </joint>

  <!-- Middle Link -->
  <link name="link1">
    <collision>
      <origin xyz="${height1/2 - axel_offset} 0 0" rpy="0 1.57075 0"/>
      <geometry>
	<cylinder length="${height1}" radius="${radius}"/>
      </geometry>
    </collision>

    <visual>
      <origin xyz="${height1/2 - axel_offset} 0 0" rpy="0 1.57075 0"/>
      <geometry>
	<cylinder length="${height1}" radius="${radius}"/>
      </geometry>
      <material name="black"/>
    </visual>

    <inertial>
      <origin xyz="${height1/2 - axel_offset} 0 0 " rpy="0 1.56075 0"/>
      <mass value="${mass}"/>
      <inertia
          ixx="${mass / 12.0 * (3*radius*radius + height1*height1)}" ixy="0.0" ixz="0.0"
          iyy="${mass / 12.0 * (3*radius*radius + height0*height1)}" iyz="0.0"
          izz="${mass / 2.0  * (radius*radius)}"/>
       </inertial>
  </link>

  <joint name="joint2" type="continuous">
    <parent link="link1"/>
    <child link="link2"/>
    <origin xyz="${height1 - axel_offset*2} 0 0 " rpy="0 0 0"/>
    <axis xyz="0 0 1"/>
    <dynamics damping="0.7"/>
  </joint>

  <!-- Top Link -->
  <link name="link2">
     <collision>
      <origin xyz="${height2/2 - axel_offset} 0 0" rpy="0 1.57075 0"/>
      <geometry>
        <cylinder length="${height2}" radius="${radius}"/>
      </geometry>
     </collision>

    <visual>
      <origin xyz="${height2/2 - axel_offset} 0 0" rpy="0 1.57075 0"/>
      <geometry>
	<cylinder length="${height2}" radius="${radius}"/>
      </geometry>
      <material name="orange"/>
    </visual>

    <inertial>
      <origin xyz="${height2/2 - axel_offset} 0 0" rpy="0 1.57075 0"/>
      <mass value="${mass}"/>
      <inertia
          ixx="${mass / 12.0 * (3*radius*radius + height2*height2)}" ixy="0.0" ixz="0.0"
          iyy="${mass / 12.0 * (3*radius*radius + height2*height2)}" iyz="0.0"
          izz="${mass / 2.0  * (radius*radius)}"/>
      </inertial>
   </link>

  <joint name="joint_sensor" type="continuous">
    <axis xyz="0 1 0" />
    <origin xyz="${height2 - axel_offset/2} 0 0" rpy="0 0 0"/>
    <parent link="link2"/>
    <child link="link_sensor"/>
    <axis xyz="0 0 1"/>
  </joint>

  <link name="link_sensor">
    <collision>
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <geometry>
	<sphere radius="${sensor_size}"/>
      </geometry>
    </collision>

    <visual>
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <geometry>
	<sphere radius="${sensor_size}"/>
      </geometry>
      <material name="red"/>
    </visual>

    <inertial>
      <mass value="1e-5" />
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <inertia ixx="1e-6" ixy="0" ixz="0" iyy="1e-6" iyz="0" izz="1e-6" />
    </inertial>
  </link>


  <transmission name="tran1">
    <type>transmission_interface/SimpleTransmission</type>
    <joint name="joint1">
      <hardwareInterface>EffortJointInterface</hardwareInterface>
    </joint>
    <actuator name="motor1">
      <hardwareInterface>EffortJointInterface</hardwareInterface>
      <mechanicalReduction>1</mechanicalReduction>
    </actuator>
  </transmission>

  <transmission name="tran2">
    <type>transmission_interface/SimpleTransmission</type>
    <joint name="joint2">
      <hardwareInterface>EffortJointInterface</hardwareInterface>
    </joint>
    <actuator name="motor2">
      <hardwareInterface>EffortJointInterface</hardwareInterface>
      <mechanicalReduction>1</mechanicalReduction>
    </actuator>
  </transmission>

</robot>
